//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PE_Admin_Library.ModelLibrary.EntityFrameworkLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class PropertyDetail
    {
        public PropertyDetail()
        {
            this.PropertyImages = new HashSet<PropertyImage>();
        }
    
        public long PropertyID { get; set; }
        public string Title { get; set; }
        public string Type { get; set; }
        public string NumberOfBedrooms { get; set; }
        public string Location { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> DateUploaded { get; set; }
        public string Status { get; set; }
    
        public virtual ICollection<PropertyImage> PropertyImages { get; set; }
    }
}
