//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PE_Admin_Library.ModelLibrary.EntityFrameworkLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class PropertyImage
    {
        public long PropertyImageID { get; set; }
        public Nullable<long> PropertyID { get; set; }
        public byte[] Image { get; set; }
    
        public virtual PropertyDetail PropertyDetail { get; set; }
    }
}
